### ISSUE TITLE
Suggestion for improving specs

### ISSUE THREAD

**Issue by cnicodeme** [ttezel/unio#14]
I like the idea to write specs in JSON :+1: 

Moreover, this can be used in a HTML web page as a documentation, just by parsing the JSON document in javascript and creating a complete and clean documentation.

But for that, I feel like the actual spec is missing some important key points, like the description of each resources and params.

Here an example of an opinion I have for adding description and then improving JSON description of REST API services :

``` javascript
{
    "name": "twitter",
    "api_root": "https://api.twitter.com/1.1",
    "resources": {
        "account/settings":{
            "path": "account/settings.json",
            "methods": [ "get" ],
            "description": "Returns settings (including current trend, geo and sleep time information) for the authenticating user.",
            "params": [
                {
                    "name": "oauth",
                    "state": "required",
                    "description": "OAuth token required to execute this request.",
                },
                {
                    "name": "count",
                    "state": "optional",
                    "description": "Specifies the number of tweets to try and retrieve, up to a maximum of 200. The value of count is best thought of as a limit to the number of tweets to return because suspended or deleted content is removed after the count has been applied. We include retweets in the count, even if include_rts is not supplied. It is recommended you always send include_rts=1 when using this API method.",
                }
            ]
        },
    // ...
}
```

Doing this, even the author of this documentation can build a documentation in just a single html page that updates itself automatically when the documentation is updated! :)

**Comment by ttezel** [comment]
hey @cnicodeme, thanks for the thoughts! You can already specify `description` entries in the spec if you want - all `unio` cares about is that you have what is detailed in the documentation. So you can go right ahead and have `description` entries (and anything else) in the spec JSON :)

**Comment by cnicodeme** [comment]
Good to know :)

Thanks.
