### ISSUE TITLE
Make the default included specs similar in structure

### ISSUE THREAD

**Issue by joustava** [ttezel/unio#16]
eg. the github spec

``` json
{
    "name": "github",
    "api_root": "https://api.github.com",
    "resources": {
        "authorizations": {
            "path": "authorizations",
            "methods": [ "post", "get" ],
            "params": [
                {
                ....
}
```

has the resource name as 'key' to the resource 'object'.

however the twitter spec defines the resource name as part of the object.
Maybe it is nice to choose one format as reference for implementations of Unio in other languages? Maybe it might also be nice to have the specs complete for those included in Unio?

**Comment by ttezel** [comment]
Yes you're right, I have updated all the specs to be consistent with one another, using the format described in the readme file. Run `npm update unio` to get the latest version with the fix.

**Comment by ttezel** [comment]
As for having complete specs, pull requests are appreciated. In the meantime, I have been adding to specs as I go along. Closing this issue since the specs are now consistent with one another.
