### ISSUE TITLE
Twitter API V1 upgrade

### ISSUE THREAD

**Issue by corotchi** [ttezel/unio#19]
Hi ttezel, when I try to use twitter from unio i get 

 [ { message: 'The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.',
       code: 68 } ] }

Is it in pipeline twitter API update ?

Thanks!

**Comment by ttezel** [comment]
Whoops, that's a quick fix. I'll get to it as soon as I find a moment (sometime this week)

**Comment by corotchi** [comment]
Thank You!! Cheers !

**Comment by ttezel** [comment]
Updated the twitter spec. Run `npm update unio` to get the latest version. I'm assuming you ran into this issue using the twitter search API?

**Comment by ttezel** [comment]
Closing. Feel free to reopen if you run into a similar issue
