### ISSUE TITLE
Question: Why not WADL

### ISSUE THREAD

**Issue by wspeirs** [ttezel/unio#7]
Why create a new description language for RESTful services? Why not use WADL: http://en.m.wikipedia.org/wiki/Web_Application_Description_Language

**Comment by nerdy-sam** [comment]
because JSON > XML ;-)

**Comment by ttezel** [comment]
The idea is to use the simpler, more readable format that unio supports. Unio's format allows it to use the Facebook, Twitter, Instagram, Github, Stackexchange, and many other REST APIs. I greatly prefer unio's format to WADL, as it is simpler & more readable (and therefore easier to maintain). If you prefer to use WADL, there are likely other clients you can use.

**Comment by kfrajtak** [comment]
Will you support API Blueprint out-of-the-box?
