### ISSUE TITLE
Create Spec for "generic" JSON schema

### ISSUE THREAD

**Issue by davidkassa** [ttezel/unio#8]
I think this is a great idea! There is currently a JSON schema draft that various validators and tools follow. If implemented this would help a lot of unknown providers quickly comply.

Resources:
http://tools.ietf.org/html/draft-zyp-json-schema-03
http://json-schema.org/implementations.html
http://www.jsonschema.net/faq.html

**Comment by ttezel** [comment]
this spec doesn't look half bad!

**Comment by ttezel** [comment]
I think the schema they provide is pretty good. With unio, you can add `description` and `type` properties to the spec like they have done in their spec (it will simply be ignored by unio). I don't see why the type of each property needs to be specified - the JSON data format already handles numbers, strings, objects, arrays etc.

**Comment by ttezel** [comment]
Closing this issue - the unio spec is simpler, and is compatible with most popular REST APIs. If really needed, it is certainly possible to transform other JSON specs to the unio format with a simple script.
